apiVersion: v1
kind: Namespace
metadata:
  name: blue-green-istio
  labels:
    istio-injection: enabled  

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: blue-green-istio
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: myapp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blue-green
  namespace: blue-green-istio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: app.demo.lab
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: myapp-service
            port: 
              number: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapp-gateway
  namespace: blue-green-istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "app.istio.demo.lab"

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp-destinationrule
  namespace: blue-green-istio
spec:
  host: myapp-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: route
          ttl: 2880s
  subsets:
  - name: blue
    labels:
      color: blue
  - name: green
    labels:
      color: green

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp-virtualservice
  namespace: blue-green-istio
spec:
  hosts:
  - "app.istio.demo.lab"
  gateways:
  - myapp-gateway
  http:
  - name: myapp-test
    match:
    - headers:
        cookie:
          regex: "^(.*?;)?(test=true)(;.*)?$"
    route:
    - destination:
        host: myapp-service
        subset: green

  - name: myapp-default
    route:
    - destination:
        host: myapp-service
        subset: blue

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-blue
  namespace: blue-green-istio
  labels:
    app: myapp
    color: blue
#    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      color: blue
#      version: v1
  template:
    metadata:
      labels:
        app: myapp
        color: blue
#        version: v1
    spec:
      containers:
      - name: myapp
        image: aramirol/blue-green-deployment:0.0.1
        ports:
        - containerPort: 80

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: myapp-deployment-green
#  namespace: blue-green-istio
#  labels:
#    app: myapp
#    color: green
#    version: v1
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: myapp
#      color: green
#      version: v1
#  template:
#    metadata:
#      labels:
#        app: myapp
#        color: green
#        version: v1
#    spec:
#      containers:
#      - name: myapp
#        image: aramirol/blue-green-deployment:0.0.1
#        ports:
#        - containerPort: 80
