apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-green
  namespace: blue-green-istio
  labels:
    app: myapp
    color: green
#    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      color: green
#      version: v2
  template:
    metadata:
      labels:
        app: myapp
        color: green
#        version: v2
    spec:
      containers:
      - name: myapp
        image: aramirol/blue-green-deployment:0.0.2
        ports:
        - containerPort: 80
