apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: istio-example-bg
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: myapp
